name: liefde
description: gif for love
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.2
  audioplayers: ^0.14.0
  # assets_audio_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/
  - assets/audio/
  - assets/naruto.gif
  - assets/1.jpg
  - assets/2.jpg
  - assets/3.jpg
  - assets/4.jpg
  - assets/5.jpg
  - assets/6.jpg
  - assets/7.jpg
  - assets/8.jpg
  - assets/9.jpg
  - assets/0.jpg
  - assets/11.jpg
  - assets/12.jpg
  - assets/13.jpg
  - assets/klaar.jpg
  - assets/shallow.jpg
  - assets/audio/lovesong.mp3
  - assets/lovesong.mp3
  fonts:
  - family: FlamanteRoma
    fonts:
    - asset: assets/fonts/Circle-Of-Love.ttf
      style: italic

